SituationCenterBackServer/Models/RoomSecurity.cs
using Common.Models.Rooms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SituationCenterBackServer.Models
{
    public class RoomSecurity
    {
        public Guid Id { get; set; }
        public PrivacyRoomType PrivacyRule { get; set; }
        public string Data { get; set; }
    }
}

SituationCenterBackServer/Models/VoiceChatModels/IConnector.cs
using System;
using System.Net;

namespace SituationCenterBackServer.Models.VoiceChatModels
{
    public interface IConnector
    {
        event Action<FromClientPack> OnRecieveData;
        event Action<ApplicationUser> OnUserConnected;
        void Start();
        void Stop();
        void SendPack(ToClientPack pack);
        void SetBindToUser(Func<string, ApplicationUser> findUserFunc);
    }
}

SituationCenterBackServer/Models/VoiceChatModels/SignInRoomInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SituationCenterBackServer.Models.VoiceChatModels
{
    public class SignInRoomInfo : ResponseData
    {
        public byte RoomId { get; set; }
        public byte ClientId { get; set; }
        public int Port { get; set; }

        public SignInRoomInfo()
        {
            Succsess = true;
        }
    }
}

SituationCenterBackServer/Models/VoiceChatModels/TCPConnector.cs
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SituationCenterBackServer.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SituationCenterBackServer.Models.VoiceChatModels
{
    public class TCPConnector : IConnector
    {

        public event Action<FromClientPack> OnRecieveData;
        public event Action<ApplicationUser> OnUserConnected;


        private readonly TcpListener _listener;

        private CancellationTokenSource _cts;
        private readonly ILogger<TCPConnector> _logger;
        private readonly Dictionary<ApplicationUser, TcpClient> _connectionForUsers = new Dictionary<ApplicationUser, TcpClient>();
        private Func<string, ApplicationUser> _findUserFunc;


        public TCPConnector(ILogger<TCPConnector> logger, IOptions<UnrealAPIConfiguration> options)
        {
            _logger = logger;
            _listener = new TcpListener(IPAddress.Any, options.Value.Port);
        }

        public void Start()
        {
            if (_cts != null)
            {
                _logger.LogWarning("Try to Start started TCPConnector");
                return;
            }
            if (_findUserFunc == null)
                throw new Exception("You must define function for find user, use SetBindToUser method for this");
            _listener.Start();
            _cts = new CancellationTokenSource();
            var token = _cts.Token;
            Task.Factory.StartNew(() => Listen(token), token);
        }

        public void Stop()
        {
            _cts.Cancel();
        }

        public void SendPack(ToClientPack pack)
        {
            if (!_connectionForUsers.ContainsKey(pack.User))
            {
                _logger.LogWarning("User " + pack.User.Email + " not found in TCP connections");
                return;
            }
            var tcpClient = _connectionForUsers[pack.User];
            if (!tcpClient.Connected)
            {
                _logger.LogWarning($"User {pack.User.Email} not connected ovet TCP");
                return;
            }
            var bytestoSend = CreateHeader(pack.Data.Length + 2).Concat(new[] { (byte)pack.PackType, pack.User.InRoomId,}.Concat(pack.Data)).ToArray();
            tcpClient.GetStream().WriteAsync(bytestoSend, 0, bytestoSend.Length).Wait();
        }
        public void SetBindToUser(Func<string, ApplicationUser> findUserFunc)
        {
            _findUserFunc = findUserFunc;
        }
        private void Listen(CancellationToken token)
        {
            while (!token.IsCancellationRequested)
            {
                _logger.LogInformation("Waiting for client...");
                var client= _listener.AcceptTcpClientAsync().Result;
                if (client != null)
                {
                    Task.Factory.StartNew(() => HandleClient(client, token), token);
                }
                token.ThrowIfCancellationRequested();
            }
        }
        private async void HandleClient(TcpClient client, CancellationToken token)
        {
            _logger.LogInformation($"Client {client.Client.RemoteEndPoint}. Waiting for initial message.");
            var buffer = new byte[1024 * 8];
            var readed = await client.ReadPacketAsync(buffer, 0, buffer.Length, token);
            if (buffer[0] != (byte) PackType.Auth)
            {
                //TODO Оповещение пользователя о проблеме
                _logger.LogWarning("Client not sended auth message!!");
                client.Dispose();
                return;
            }
            var userId = Encoding.UTF8.GetString(buffer, 1, readed - 1);
            var user = _findUserFunc(userId);
            if (user == null)
            {
                //TODO Оповещение пользователя о проблеме
                _logger.LogWarning($"Recieved pack with unreal parameters: userId: {userId}");
                client.Dispose();
                return;
            }
            _logger.LogInformation($"Connected user {user.UserName}");
            _connectionForUsers[user] = client;
            OnUserConnected(user);
            do
            {
                readed = await client.ReadPacketAsync(buffer, 0, buffer.Length, token);
                _logger.LogDebug($"Recieved {readed} bytes from {client.Client.RemoteEndPoint}, {user.UserName}");
                OnRecieveData?.Invoke(new FromClientPack()
                {
                    User = user,
                    PackType = (PackType)buffer[0],
                    Data = buffer.Skip(1).Take(readed-1).ToArray()
                });
            } while (readed != 0 && !token.IsCancellationRequested);
            client.Dispose();
            _logger.LogInformation($"User {user.Email} disconnected ");
            token.ThrowIfCancellationRequested();
        }

        private byte[] CreateHeader(int value)
        {
            return new byte[] { (byte)(value >> 8), (byte)(value)};
        }
    } 
}

SituationCenterBackServer/Controllers/StorageFilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SituationCenterBackServer.Models;
using SituationCenterBackServer.Models.StorageModels;
using SituationCenterBackServer.Services;
using Storage.Interfaces;
using System.Linq;
using IO = System.IO;

namespace SituationCenterBackServer.Controllers
{
    [Authorize]
    [Route("storagefiles/[action]/{*pathToFolder}")]
    public class StorageFilesController : Controller
    {
        private readonly IStorage storageManager;
        private readonly UserManager<ApplicationUser> userManager;

        public StorageFilesController(IStorage storageManager,
            UserManager<ApplicationUser> userManager)
        {
            this.storageManager = storageManager;
            this.userManager = userManager;
        }

        public IActionResult Index(string pathToFolder)
        {
            pathToFolder = pathToFolder ?? "";
            string userId = GetUserId();

            var content = storageManager.GetRootDirectory("Moq token", userId);
            
            return View(new DirectoryContent { Directories = content.Directories.ToList(), Files = content.Files.ToList()});
        }

        public IActionResult Add(string pathToFolder, IFormFile file)
        {
            pathToFolder = pathToFolder ?? "";
            string userId = GetUserId();

            var targetFolder = storageManager.GetDirectory("Moq token", userId, pathToFolder);
            targetFolder.CreateFile(file.FileName, file.OpenReadStream());
            return RedirectToAction("index");
        }

        private string GetUserId()
        {
            return userManager.GetUserId(User);
        }
    }
}

SituationCenterBackServer/Views/Logs/Index.cshtml
@{
}

<h3 id="status"></h3>
<button id="sendlog" class="btn btn-lg">Отправить лог</button>
<input type="text" id="findfield" />
<table class="table-bordered table">
    <thead>
        <tr>
            <th>Категория</th>
            <th>Уровень логирования</th>
            <th>Информация</th>
        </tr>
    </thead>
    <tbody id="body"></tbody>
</table>
<script>
    var sort = function () {
        var filter = field.value.toUpperCase();
        var tr = document.getElementById("body").getElementsByTagName("tr");
        for (var i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    };

    var socket;
    var connectcount = 0;
    var status = document.getElementById("status");
    var initSocket = function () {
        socket = new WebSocket("ws://" + window.location.host +"/logs/connect");
        connectcount++;
        status.innerHTML = "Подключение " + connectcount;
        socket.onmessage = function (args) {
            var message = JSON.parse(args.data);
            document.getElementById("body").insertAdjacentHTML("afterbegin", "<tr><td>" + message.CategoryName + "</td><td>" + message.LogLevel + "</td><td>" + message.Message + "</td></tr>")
            sort();
        }
        socket.onopen = function (args)
        {
            connectcount = 0;
            status.innerHTML = "Подключено";
        }
        socket.onclose = function (args) {
            initSocket();
        }
    }
    initSocket();
    var field = document.getElementById("findfield");
    field.onkeyup = sort;
</script>

SituationCenterBackServer/Views/StorageFiles/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model SituationCenterBackServer.Models.StorageModels.DirectoryContent
    @*Говорим, что отображаем такую модель на страничке*@
<h2>Index</h2>
<h3>Папки</h3>
    @*Используем циклы прямо в разметке, цикл отработает, и добавит необходимую HTML разметку
    Таким образом, ты пишешь разметку, не думая, какие именно данные тебе придут.
    Страничка сама отрисовывается каждый раз.*@
@*Справка по этому инструменту : https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor*@
@*Чтобы проверить, как это работает, запусти приложение, и перейли по ссылке http://localhost/storage*@
<ol>
    @foreach(var directory in Model.Directories)
    {
        <li>@directory.Name</li>
    }
</ol>
<h3>Файлы</h3>
<ol>
    @foreach (var file in Model.Files)
    {
        <li>@file.Name</li>
    }
</ol>
<h3>Добавить в эту директорию</h3>
<form asp-action="Add" asp-controller="StorageFiles" method="post" enctype="multipart/form-data">
    <input type="file" name="file" />

    <input type="submit" value="Load" class="btn" />
</form>